### ISSUE TITLE
Fails to build with Linux 4.10+

### ISSUE THREAD

**Issue by mikroskeem** [sabotage-linux/libnl-tiny#2]
According to [this site](https://elixir.bootlin.com/linux/v4.9.142/source/include/uapi/linux/genetlink.h), GENL_ID_GENERATE is not available since 4.10+ kernels, which causes libnl-tiny fail to compile.

```
gcc -DLIBNL1_COMPAT  -c -o unl.o -Iinclude -O2 -fPIC unl.c
In file included from genl_ctrl.c:23:
include/netlink/genl/family.h: In function 'genl_family_get_id':
include/netlink/genl/family.h:62:10: error: 'GENL_ID_GENERATE' undeclared (first use in this function); did you mean 'GENL_ID_PMCRAID'?
   return GENL_ID_GENERATE;
          ^~~~~~~~~~~~~~~~
          GENL_ID_PMCRAID
include/netlink/genl/family.h:62:10: note: each undeclared identifier is reported only once for each function it appears in
In file included from genl_family.c:23:
include/netlink/genl/family.h: In function 'genl_family_get_id':
include/netlink/genl/family.h:62:10: error: 'GENL_ID_GENERATE' undeclared (first use in this function); did you mean 'GENL_ID_PMCRAID'?
   return GENL_ID_GENERATE;
          ^~~~~~~~~~~~~~~~
          GENL_ID_PMCRAID
include/netlink/genl/family.h:62:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:38: genl_family.o] Error 1
make: *** Waiting for unfinished jobs....
In file included from genl_mngt.c:87:
include/netlink/genl/family.h: In function 'genl_family_get_id':
include/netlink/genl/family.h:62:10: error: 'GENL_ID_GENERATE' undeclared (first use in this function); did you mean 'GENL_ID_PMCRAID'?
   return GENL_ID_GENERATE;
          ^~~~~~~~~~~~~~~~
          GENL_ID_PMCRAID
include/netlink/genl/family.h:62:10: note: each undeclared identifier is reported only once for each function it appears in
In file included from unl.c:5:
include/netlink/genl/family.h: In function 'genl_family_get_id':
make: *** [Makefile:38: genl_ctrl.o] Error 1
include/netlink/genl/family.h:62:10: error: 'GENL_ID_GENERATE' undeclared (first use in this function); did you mean 'GENL_ID_PMCRAID'?
   return GENL_ID_GENERATE;
          ^~~~~~~~~~~~~~~~
          GENL_ID_PMCRAID
include/netlink/genl/family.h:62:10: note: each undeclared identifier is reported only once for each function it appears in
make: *** [Makefile:38: genl_mngt.o] Error 1
make: *** [Makefile:38: unl.o] Error 1
==> ERROR: A failure occurred in build().
    Aborting...
```

**Comment by mikroskeem** [comment]
https://www.spinics.net/lists/netdev/msg423041.html

**Comment by rofl0r** [comment]
thanks for info. please let me know if the issue is resolved.

**Comment by mikroskeem** [comment]
lol, I thought it's going to end up with some behavioural changes in code, but no.

Nevertheless thanks a lot :smile:

**Comment by rofl0r** [comment]
does it mean it works as expected ?

**Comment by mikroskeem** [comment]
as much as i tested with iw and wpa_supplicant yes

**Comment by rofl0r** [comment]
as for behavioral changes, that's certainly not necessary, as both the answer on LKML suggests, as well as my experience using libnl-tiny since half a year on kernel 4.14 without issues (we use our kernel-headers package based on kernel 3.something, that's why nobody noticed a build error so far).
